spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
#      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
#      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#    bootstrap-servers: localhost:9092  # Kafka 서버 주소
#    consumer:
#      max-poll-records: 5
#      enable-auto-commit: false # 수동 커밋 설정
#      group-id: product_group                # Consumer 그룹 ID
#      auto-offset-reset: earliest       # Offset 리셋 정책
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: localhost:9092  # Kafka 서버 주소
#    consumer:
#      max-poll-records: 5
#      enable-auto-commit: false # 수동 커밋 설정
#      group-id: product_group                # Consumer 그룹 ID
#      auto-offset-reset: earliest       # Offset 리셋 정책
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
