spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  kafka:
    consumer:
      enable-auto-commit: false # 수동 커밋 설정
      bootstrap-servers: localhost:9092  # Kafka 서버 주소
      group-id: group_id                # Consumer 그룹 ID
      auto-offset-reset: earliest       # Offset 리셋 정책
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  kafka:
    consumer:
      enable-auto-commit: false # 수동 커밋 설정
      bootstrap-servers: localhost:9092  # Kafka 서버 주소
      group-id: group_id                # Consumer 그룹 ID
      auto-offset-reset: earliest       # Offset 리셋 정책
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
